### ISSUE TITLE
Hitting Ctrl-C during sudo prompt causes a segmentation fault

### ISSUE THREAD

**Issue by sebadoom** [google/fscrypt#78]
Test case: 
1. `sudo echo lol`
2. Hit Ctrl-C to cancel password input.

Result:
```
[sudo] password for seba: 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fa539940f11]

runtime stack:
runtime.throw(0x7fa53576536c, 0x2a)
	/usr/lib/go/src/runtime/panic.go:605 +0x97
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:351 +0x2bc

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x7fa53575b580, 0xc4200c1cb8, 0x29)
	/usr/lib/go/src/runtime/cgocall.go:132 +0xea fp=0xc4200c1c88 sp=0xc4200c1c48 pc=0x7fa5355f374a
github.com/google/fscrypt/pam._Cfunc_copyIntoSecret(0x0, 0x0)
	github.com/google/fscrypt/pam/_obj/_cgo_gotypes.go:106 +0x4c fp=0xc4200c1cb8 sp=0xc4200c1c88 pc=0x7fa53571b70c
github.com/google/fscrypt/pam.(*Handle).SetSecret.func1(0x0, 0x7fa53571c7a1)
	/home/seba/.cache/pacaur/fscrypt-git/src/go/src/github.com/google/fscrypt/pam/pam.go:98 +0x62 fp=0xc4200c1cf0 sp=0xc4200c1cb8 pc=0x7fa53571cfc2
github.com/google/fscrypt/pam.(*Handle).SetSecret(0xc42000c9e0, 0x7fa53575dfc3, 0xf, 0x0, 0x0, 0x0)
	/home/seba/.cache/pacaur/fscrypt-git/src/go/src/github.com/google/fscrypt/pam/pam.go:98 +0x2d fp=0xc4200c1d38 sp=0xc4200c1cf0 pc=0x7fa53571c65d
main.Authenticate(0xc42000c9e0, 0xc4200108a0, 0x0, 0x0)
	/home/seba/.cache/pacaur/fscrypt-git/src/go/src/github.com/google/fscrypt/pam_fscrypt/pam_fscrypt.go:75 +0x256 fp=0xc4200c1da8 sp=0xc4200c1d38 pc=0x7fa5357576c6
main.RunPamFunc(0x7fa535a01df8, 0x55af85c4b080, 0x0, 0x0, 0x0)
	/home/seba/.cache/pacaur/fscrypt-git/src/go/src/github.com/google/fscrypt/pam_fscrypt/run_fscrypt.go:82 +0x20c fp=0xc4200c1e40 sp=0xc4200c1da8 pc=0x7fa53575915c
main.pam_sm_authenticate(0x55af85c4b080, 0x8000, 0x0, 0xc400000008)
	/home/seba/.cache/pacaur/fscrypt-git/src/go/src/github.com/google/fscrypt/pam_fscrypt/pam_fscrypt.go:262 +0x4b fp=0xc4200c1e78 sp=0xc4200c1e40 pc=0x7fa535758dab
main._cgoexpwrap_058fc3b736e8_pam_sm_authenticate(0x55af85c4b080, 0x8000, 0x0, 0x0)
	github.com/google/fscrypt/pam_fscrypt/_obj/_cgo_gotypes.go:62 +0x47 fp=0xc4200c1ea8 sp=0xc4200c1e78 pc=0x7fa5357571a7
runtime.call32(0x0, 0x7fff085bf0e8, 0x7fff085bf180, 0x20)
	/usr/lib/go/src/runtime/asm_amd64.s:509 +0x3d fp=0xc4200c1ed8 sp=0xc4200c1ea8 pc=0x7fa535646f7d
runtime.cgocallbackg1(0x0)
	/usr/lib/go/src/runtime/cgocall.go:305 +0x1a0 fp=0xc4200c1f58 sp=0xc4200c1ed8 pc=0x7fa5355f3b00
runtime.cgocallbackg(0x0)
	/usr/lib/go/src/runtime/cgocall.go:187 +0x95 fp=0xc4200c1fc0 sp=0xc4200c1f58 pc=0x7fa5355f38c5
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:762 +0x9a fp=0xc4200c1fe0 sp=0xc4200c1fc0 pc=0x7fa53564858a
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200c1fe8 sp=0xc4200c1fe0 pc=0x7fa535649801
[1]    4513 abort      sudo echo lol
```

**Comment by fancytenseletters** [comment]
What system is this?

**Comment by josephlr** [comment]
@sebadoom if @fancytenseletters's suggestion doesn't fix your problem can you [add the `debug` option for the `pam_fscrypt` module](https://github.com/google/fscrypt/blob/master/CONTRIBUTING.md#reporting-an-issue-or-discussing-design)? The info that gets printed to the syslog (usually at `/var/log/syslog`) can help me debug this problem.

**Comment by sebadoom** [comment]
I can confirm the change recommended above solves this segmentation fault. Should this be documented somewhere? I can contribute the necessary documentation changes.

**Comment by fancytenseletters** [comment]
I think it would be best to document it in Arch wiki which omits fscrypt completely atm:
https://wiki.archlinux.org/index.php/Ext4#Using_file-based_encryption

**Comment by sebadoom** [comment]
Yes, I had planned to do this, as well as update the general Encryption page in Arch's wiki. As soon as I get some time I'll do it. I'll close this bug since it seems resolved. Thanks.
